### ISSUE TITLE
strict_types declaration must be the very first statement in the script

### ISSUE THREAD

**Issue by oojacoboo** [sebastianbergmann/resource-operations#3]
strict_types declaration must be the very first statement in the script in ~/vendor/sebastian/resource-operations/build/generate.php on line 2

**Comment by oojacoboo** [comment]
#4

**Comment by sebastianbergmann** [comment]
There is no issue here.

**Comment by oojacoboo** [comment]
PHP 7.4 with preloading begs to differ
